app/routes.php
<?php
Event::listen('Universal.Creation.Events.TenantCreated','NotificationsController@store');
Event::listen('Universal.Creation.Events.RentPaid','RentPaysController@store');
Event::listen('Universal.Creation.Events.DailyPaid','RentPaysController@store');
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
// Route::get('/', 'HomeController@showWelcome');
Route::resource('/','WelcomeController');
Route::get('login',array(
		'as' => 'login_page',
		'uses' => 'SessionsController@create'
	));
Route::post('login',array(
		'as' => 'login_path',
		'uses' => 'SessionsController@store'
	));
Route::get('logout','SessionsController@destroy');
Route::controller('page','PagesController');
Route::get('download',function(){
	$file = $_GET['file'];
	return Response::download($file);
});
Route::get('view', function()
{
	$file = $_GET['file'];
	return Redirect::to($file);
});

// GROUP ROUTES

Route::group(array('before'=>'auth'), function(){
Route::resource('users','UsersController');
Route::resource('admin','AdminController');
Route::resource('admin.staffs','StaffsController');
Route::resource('admin.plots','PlotsController');
Route::resource('plots','PlotsController');
Route::resource('agents','AgentsController');
Route::resource('staffs','StaffsController');
Route::resource('payments','PaymentsController');
Route::resource('customers.payments','PaymentsController');
Route::resource('cocuments', 'DocumentsController');
Route::resource('customers', 'CustomersController');
Route::resource('agents.customers', 'CustomersController');
Route::resource('search', 'SearchController');
Route::resource('partners', 'PartnersController');


Route::get('transactions/checkdate',array('as'=>'checkdate','uses'=>'TransactionsController@getCheckdate'));
Route::resource('transactions', 'TransactionsController');

Route::resource('paying', 'DailyTransactionsController');
Route::resource('prospectives', 'ProspectivesController');

Route::get('tenants/vacate/{id}/{hid}',array('as'=>'vacate','uses'=>'TenantsController@getVacate'));
Route::get('tenants/kill/{id}',array('as'=>'kill','uses'=>'TenantsController@getKill'));
Route::resource('tenants.rents-paid','TenantsController@getRents');
Route::resource('tenants', 'TenantsController');

Route::resource('tenants.payments', 'TenanPaymentsController');

Route::resource('land-lords.rents-paid','LandlordsController@getRents');
Route::resource('land-lords', 'LandlordsController');

Route::resource('compounds', 'CompoundsController');
Route::resource('houses', 'HousesController');
Route::resource('notifications', 'NotificationsController');
Route::get('data-entry', array('as'=>'data_entry', 'uses'=>'PagesController@showData'));
Route::resource('estates', 'EstatesController');
Route::resource('estates.plots', 'EstatesController');
Route::resource('rent-pays', 'RentPaysController');
Route::resource('luwas', 'LuwasController');
});
#THIS IS THE TESTING PART BELOW
// Event::listen('illuminate.query',function($query){
// echo '<pre style="margin:200px 80px">';
// print_r($query);
// echo '</pre>';
// });

app/models/Customer.php
<?php

class Customer extends \Eloquent {
	protected $primaryKey = 'cust_id';
	protected $fillable = ['cust_id',
'cust_plotID',
'cust_downpayment',
'cust_partnerID',
'cust_personID',
'cust_ruleID',
'cust_transID',
'cust_status',
'cust_lanID',
'cust_agenID',
'cust_payID',
'cust_deleted',
'cust_visible',
'total_payment',
'period',
'Balance',
'Monthly_Fee',
'Commencing',
'pay_type'
];


	public function person(){
		return $this->belongsTo('Person','cust_personID','id');
	}
	public function plots(){
		return $this->hasMany('Plot','plot_cusID','cust_id');
	}
	public function payments(){
		return $this->hasMany('Payment','paym_custID','cust_id');
	}
	public function transactions(){
		return $this->hasMany('Transaction','trans_custID','cust_id');
	}
	public function documents(){
		return $this->hasMany('Document','entity_ID','cust_id');
	}
	public function kin(){
		return $this->hasOne('Kin');
	}
}

app/controllers/CustomersController.php
<?php
use Intervention\Image\ImageManagerStatic as Image;
class CustomersController extends \AdminController {

	protected $data = array();
	/**
	 * Display a listing of the resource.
	 * GET /customers
	 *
	 * @return Response
	 */
	public function index()
	{
		$cus  = Customer::with('person.contacts','plots.estate')->get();
		$customers = $cus ? $cus->toArray() : [];
		$this->layout->content = View::make('admin.customers.index')->with('customers',$customers);
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /customers/create
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('admin.customers.create');
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /customers
	 *
	 * @return Response
	 */
	public function store()
	{
		
		$input = Input::all();
		$person = array();
		$staff = array();
		$address = array();
		$contact = array();
		$customer = array();

		$done = false;
		// var_dump(Request::segment(2));
		// dd($input);
		// die();
		if ($input) :
			foreach ($input as $k => $table) {
				if (is_array($table)) {
					if ($k == 'person') {
						$V = new services\validators\Person($table);
						if($V->passes()){
							$person = Person::create(array(
							'pers_fname' => $table['fname'], 
							'pers_mname' => ($table['mname']) ?: null, 
							'pers_lname' => $table['lname'], 
							'pers_type' => 'Customer', 
							'pers_DOB' => $table['dob'], 
							'pers_gender' => $table['Pers_Gender'], 
							'pers_nationality' => $table['Pers_Nationality'], 
							'pers_NIN' => $table['nin_id']
							));
							if ($person->id) {
								$done = true;
							}
						}else{
							$errors = $V->errors;
							return Redirect::back()->withErrors($errors)->withInput();							
						}


					}
					if ($k == 'address') {
						$address = $table;
						if ($person->id) {
							$address = array_add($address, 'Addr_EntityID', $person->id);
							$address = array_add($address, 'Addr_EntityType', 'Person');
							$V = new services\validators\Address($table);
							if($V->passes()){
								$address = Address::create($address);
							}
						}
						$errors = $V->errors;

					}
					if ($k == 'contact') {

						

						if ($person->id) {

							$V = new services\validators\Contact($table);
							foreach ($table as $key => $value) {
								if($V->passes()){

									if(!empty($value)){
										$contact = Contact::create(array(
										'Cont_EntityID' => $person->id,	
										'Cont_EntityType' => 'Person',	
										'Cont_Contact' => $value,	
										'Cont_ContactType' =>  $key	
										));

									$contact = $contact->toArray();
									}
								}
							}
							$errors = $V->errors;
						}
					}
				if ($k == 'cust') {
						#loop hole here not comming in values controlls
						if(!empty($table['cust_plotID'])):

							$price  = Plot::find($table['cust_plotID'])->plot_price;
							$customer   = Customer::create(array(
								'cust_personID'=> $person->id,
								'cust_plotID'=> (!empty($table['cust_plotID']))? $table['cust_plotID'] : 0, #view drop down select
								'cust_downpayment'=> $table['cust_downpayment'],
								'period' => $table['period'],
								'pay_type' => $table['pay_type'],
								'Monthly_Fee' => ($price - $table['cust_downpayment']) / $table['period'],
								'Commencing' => $table['pay_commencing']
							));
							if (!empty($customer)):

								$plot = Plot::find( $customer->cust_plotID );
								$plot->plot_availability = 'not-available';
								$plot->plot_status = 1;
								$plot->plot_cusID = (isset($customer->cust_id))? $customer->cust_id : 0;
								$plot->save();
							endif;
						else:
								$customer   = Customer::create(array(
									'cust_personID'=> $person->id,
									'cust_plotID'=> ($table['cust_plotID']) ?: 0, #view drop down select
									'cust_downpayment'=> $table['cust_downpayment'],
									'period' => $table['period'],
									'pay_type' => $table['pay_type'],
									'Commencing' => $table['pay_commencing']
								));
						endif;# if there is plot number

					}# end of customer
				if ($k ==  'kin') {
					Kin::create(array(
						'fname' => $table['fname'],
						'mname' => $table['mname'],
						'lname' => $table['lname'],
						'contacts' => $table['contact'],
						'customer_id' => $customer->cust_id
					));
				}


				}
			} #end of loop

			if($done){
				

					if ($input['photo']) {

							$not = 'media'.DS.'customer'.DS.$person->pers_fname.'_'.$person->pers_mname.'_'.$person->pers_lname.'_'.$person->id;
							$foldername = DS.$not.DS;
							// $full_dir = $foldername.'img'.DS.'full';

							$path = base_path().$foldername ;
							$thumbnail_dir = $not.DS.'img'.DS.'thumbnail'.DS;
							$fileexten = Input::file('photo')->getClientOriginalExtension();
							$filename = Input::file('photo')->getClientOriginalName();
							// dd($path);
							$shortened = base_convert(rand(10000,99999), 10, 36);
							$rename = $person->pers_fname.'_'.$shortened.'_photo_.'.$filename;
							$filetyp = Input::file('photo')->getMimeType();
							$fileexten = Input::file('photo')->getClientOriginalExtension();
							$uploaded = false;

							if ((File::exists($path)) && ( File::exists( $path.DS.'img'.DS ) ) && ( File::exists( $path.DS.'img'.DS.'thumbnail') ) ) {

								Input::file('photo')->move($path.DS.'img'.DS, $rename);

									#notice #01
										// there was a problem when trying to resize the image. the fix is go in the project dir (html but ! include)

									// we resize (250 X 300)
									$img = Image::make($not.$rename);
									$img->resize(250 , 300);
									$img->save($thumbnail_dir.$rename);	// we move to thumnails

								// store in the database
								Document::create(array(
										'title' => 'profile picture' ,
										'entity_type' => 'Person',
										'entity_ID' => $person->id,
										'type' => 'Photo',
										'fullpath' => $path.DS.'img'.DS.$rename,
										'filename' => $filename,
										'foldername' => $not,
										'extension' => $fileexten,
										'filetype' => $filetyp,
										'thumnaildir' => $thumbnail_dir.$rename
									));
								
								# code...
							}else{
								mkdir($path, 0755, true);
								mkdir($path.DS.'img'.DS, 0755, true);
								mkdir($path.DS.'img'.DS.'thumbnail', 0755, true);
								Input::file('photo')->move($path.DS.'img'.DS , $rename);
									// we resize (250 X 300)
									// dd($not.DS.$rename);
									$img = Image::make($not.DS.'img'.DS.$rename);
									$img->resize(250 , 300);
									$img->save($thumbnail_dir.$rename);	// we move to thumnails

								// store in the database
								Document::create(array(
										'title' => 'profile picture' ,
										'entity_type' => 'Person',
										'entity_ID' => $person->id,
										'type' => 'Photo',
										'fullpath' =>  $path.DS.'img'.DS.$rename,
										'filename' => $filename,
										'foldername' => $not,
										'extension' => $fileexten,
										'filetype' => $filetyp,
										'thumnaildir' => $thumbnail_dir.$rename
									));
							}
					} #end of photo


					if ($input['document']) {


							$not = 'media'.DS.'customer'.DS.$person->pers_fname.'_'.$person->pers_mname.'_'.$person->pers_lname.'_'.$person->id;
							$foldername = DS.$not.DS;
							// $full_dir = $foldername.'img'.DS.'full';
							
							$path = base_path().$foldername ;
							$fileexten = Input::file('document')->getClientOriginalExtension();
							$filename = Input::file('document')->getClientOriginalName();
							// dd($path);
							$shortened = base_convert(rand(10000,99999), 10, 36);
							$rename = $person->pers_fname.'_'.$shortened.'_document_.'.$filename;
							$filetyp = Input::file('document')->getMimeType();
							$fileexten = Input::file('document')->getClientOriginalExtension();
							$uploaded = false;

							if ( File::exists($path)  && ( File::exists( $path.DS.'document'.DS ) ) )  {

								Input::file('document')->move($path , $rename);

									#notice #01
										// there was a problem when trying to resize the image. the fix is go in the project dir (html but ! include)

									// we resize (250 X 300)
									// $img = Image::make($not.$rename);
									// $img->resize(250 , 300);
									// $img->save($thumbnail_dir.$rename);	// we move to thumnails

								// store in the database
								Document::create(array(
										'title' => $filename ,
										'entity_type' => 'Person',
										'entity_ID' => $person->id,
										'type' => 'Document',
										'fullpath' => $path.$rename,
										'filename' => $filename,
										'foldername' => $not,
										'extension' => $fileexten,
										'filetype' => $filetyp
									));
								
								# code...
							}else{
								File::exists($path) ?: mkdir($path, 0755, true);
								mkdir($path.DS.'document'.DS, 0755, true);
								Input::file('document')->move($path.DS.'document'.DS , $rename);
									// we resize (250 X 300)
									// $img = Image::make($not.$rename);
									// $img->resize(250 , 300);
									// $img->save($thumbnail_dir.$rename);	// we move to thumnails

								// store in the database
								Document::create(array(
										'title' => $filename ,
										'entity_type' => 'Person',
										'entity_ID' => $person->id,
										'type' => 'Document',
										'fullpath' => $path.$rename,
										'filename' => $filename,
										'foldername' => $not,
										'extension' => $fileexten,
										'filetype' => $filetyp
									));
							}
					} #end of photo
				if(isset($input['agent_id'])):
					if (!empty($input['cust']['cust_plotID'] && !empty($input['agent_id']))) {
						$plot = Plot::find( $input['cust']['cust_plotID'] );
						$plot->plot_agenID = $input['agent_id'];
						$plot->save();
					}
				endif;
				Flash::message("Successfully added a Customer");
				return Redirect::back();
			}else{

app/views/admin/customers/edit.blade.php
<?php #page specific processing
$image = array();
$person =  array();
$contacts = array();
$documents =  array();
$fullname = '';
$customer_id = $customer['cust_id'];
$kin = (!empty($customer['kin']))? $customer['kin'] : [];
    if(isset($customer) && !empty($customer)):
        $person = $customer['person'];
        $addresses = $person['addresses'];
        $contacts = $customer['person']['contacts'];
        $fullname = ucwords($person['pers_fname'] .'  '. $person['pers_mname'].' '.$person['pers_lname']);
        foreach ($customer as $key => $value) {
           if ($key == 'person') {
              $person = $value;
           }
        }
    endif;

    if (!empty($person['documents'])) {
       foreach ($person['documents'] as $d => $doc) {
            if ($doc['type'] == 'Photo') {
               $image = $doc;
            }else{
                $documents[] = $doc;
            }
       }
    }

 ?>
@include('templates/top-admin')
@section('content')
@include('__partials/modal-add-landpayment')
   <div class="scope">
        <div class="hedacont">
            <div class="navbar">
                <div class="navbar-inner" id="scopebar">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target="navbar-responsive-collapse">
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </a>
                        <a class="brand" href="">Customer Name : {{ucwords("{ $fullname }")}}</a>
                        <div class="nav-collapse collapse navbar-responsive-collapse">
                          <ul class="nav">  
                            <li><a href="{{route('customers.show',$customer['cust_id'])}}#basic">General</a> </li>
                            <li><a href="{{route('customers.show',$customer['cust_id'])}}#transactions">Transactions</a></li>
                            <li><a href="{{route('customers.show',$customer['cust_id'])}}#payments">Payments</a></li>
                            <li><a href="{{route('customers.show',$customer['cust_id'])}}#plots">Plots</a></li>
                            <li><a href="{{route('customers.edit',$customer['cust_id'])}}">Edit</a> </li>
                          </ul>
                        </div><!-- /.nav-collapse -->
                    </div>
                </div><!-- /navbar-inner -->
            </div> 
            <div class="c-header">
                <?php if (!empty($image)): ?>
                    <ul class="thumbnails" id="thmb">
                        <li class="span2">
                          <a href="#" class="thumbnail">
                           {{HTML::image($image['thumnaildir'])}}
                          </a>
                        </li>
                    </ul> 

                <?php endif ?>  
            </div>           
        </div>  
    </div>  <!-- end of scope -->

    <div class="content-details clearfix">
    	<div class="cc clearfix">
    		    		<h3>Editing Tenant</h3>
    		<hr>

	        <ul class="thumbnails">
	          <li class="row">
	            <div class="thumbnail">
	              <div class="caption">
	                <h3>Edit Personal</h3>
	                <hr>
				{{Form::model($person, ['route'=>[ 'customers.update' , $customer['cust_id']  ], 'method'=>'PATCH'],['class'=>'form-snippet'])}}

					<div class="level details">

						<div class="first">
							<div>
								{{Form::label('pers_fname','First Name')}}
								{{Form::text('pers_fname',null,['class'=>'input-xlarge','placeholder'=>'Enter first name','required'=>1])}}
							</div>
							<div>
								{{Form::label('pers_mname','Middle Name')}}
								{{Form::text('pers_mname',null,['class'=>'input-xlarge','placeholder'=>'Enter middle name'])}}
							</div>
							<div>
								{{Form::label('pers_lname','Last Name')}}
								{{Form::text('pers_lname',null,['class'=>'input-xlarge','placeholder'=>'Enter last name','required'=>1])}}
							</div>							
						</div>
					</div>
					<div class="level details">
						<span>Bio </span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('pers_DOB','Birthday ( year-month-day )')}}
								{{Form::text('pers_DOB',null,['class'=>'input-xlarge' ])}}
							</div>
							<div>
								{{Form::label('pers_ethnicity','Ethniticity')}}
								<select name="pers_ethnicity" id="enit" class="input-xlarge">
									<?php $countries = Variable::domain('Pers_Ethnicity')->toArray();  ?>
									@foreach ($countries as $key => $country)
									<option>{{$country['Vari_VariableName']}}</option>
									@endforeach
								</select>
							</div>
							<div>
								{{Form::label('pers_nationality','Nationality')}}
								<select name="pers_nationality" id="nation" class="input-xlarge">
									<?php $countries = Variable::domain('Country')->toArray();  ?>
									@foreach ($countries as $key => $country)
									<option>{{$country['Vari_VariableName']}}</option>
									@endforeach
								</select>
							</div>
							<div>
								{{Form::label('pers_gender','Gender')}}
								{{Form::select('pers_gender', array('male' => 'Male','female' => 'Female'));}}
							</div>
						</div>
					</div>

					<div class="level details">
						<span>Identification details</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('pers_NIN','Nation id number / passport number')}}
								{{Form::text('pers_NIN',null,['class'=>'input-xlarge span6','placeholder'=>'NIN number or passport number'])}} 
							</div>
						</div>
					</div>

	                <hr>
					{{Form::hidden('type','person')}} 
					{{Form::hidden('person_id',$person['id'])}} 
	                <button class="btn btn-primary">Save Changes</button>
					<button type="reset" class="btn">reset</button>
	              </div>
	            </div>
	            {{Form::close()}}
	          </li>  
	          
	        </ul>
	        <ul class="thumbnails">
<li class="span7">
	            <div class="thumbnail">
	              <div class="caption">
	                <h3>Edit Address</h3>
	                <hr>
						{{Form::model($person['addresses'][0], ['route'=>[ 'customers.update' , $person['addresses'][0]['Addr_AddressID'] ], 'method'=>'PATCH'],['class'=>'form-snippet'])}}
						<div class="level details">
							<span>Address</span>
							<hr>
							<div class="first ">
								<div>
									{{Form::label('Addr_Town','Town')}}
									{{Form::text('Addr_Town',null,['class'=>'input-xlarge','placeholder'=>'Enter town'])}}
								</div>
								<div>
									{{Form::label('Addr_District','District')}}
									<select name="Addr_District" id="region">
										<?php $countries = Variable::domain('Addr_District')->toArray();  ?>
										@foreach ($countries as $key => $country)
										<option>{{$country['Vari_VariableName']}}</option>
										@endforeach
									</select> 
								</div>
								<div>
									{{Form::label('Addr_AddressStreet','street')}}
									{{Form::text('Addr_AddressStreet',null,['class'=>'input-xlarge','placeholder'=>'Enter street'])}}
								</div>
							</div>
						</div>
	                <hr>
	                {{Form::hidden('type','address')}} 
					{{Form::hidden('address_id', $person['addresses'][0]['Addr_AddressID'] )}} 
	                <button class="btn btn-primary">Save Changes</button>
					<button type="reset" class="btn">reset</button>
	              </div>
	            </div>
	            {{Form::close()}}
	          </li> 



	          <li class="span7">
	            <div class="thumbnail">
	            	@if (isset($image['thumnaildir']))
	      				{{HTML::image($image['thumnaildir'])}}
	      			@endif
	              <div class="caption">
				{{Form::model($image, ['route'=>['customers.update', $customer['cust_id'] ], 'files'=>true,'method'=>'PATCH'],['class'=>'form-snippet'])}}
					{{Form::hidden('foldername')}}
					{{Form::hidden('fullpath')}}
					{{Form::hidden('thumnaildir')}}
					<div class="level details">
						<span>Profile picture</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('photo','Photo')}}
								{{Form::file('photo')}}
							</div>	
						</div>
					</div>

	                <hr>
					@if(isset($image['id']))
					{{Form::hidden('image_id', $image['id'])}} 
					@else
					{{Form::hidden('person_id',$person['id'])}}
					{{Form::hidden('folder',$person['pers_fname'] .'_'. $person['pers_mname'].'_'.$person['pers_lname'].'_'.$person['id'] )}} 
					@endif
	                {{Form::hidden('type','image')}} 
	                <button class="btn btn-primary">Save Changes</button>
					<button type="reset" class="btn">reset</button>
	           
	              </div>
	            </div>
	             {{Form::close()}}
	          </li>  






  
	        </ul>
    	</div>
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/customers/index.blade.php
@include('templates/top-admin')
@section('content')
	<div class="c-header cc">
		<h3>Customers</h3>
	</div>
	<div class="cc">
		<table class="table">
			<thead>
				<tr>
					<th>#</th>
					<th>Customer Name</th>
					<th>Nationality</th>
					<th>Plot Number</th>
					<th>Gender</th>
					<th>action</th>
				</tr>
			</thead>
			<tbody>
				<?php if (!empty($customers)): ?>
					<?php foreach ($customers as $key => $value): ?>
					<tr>
						<td>{{$key+1}}</td>
						<td>
<a href="{{route('customers.show',$value['cust_id'])}}"><?php echo ucwords($value['person']['pers_fname'] .'  '. $value['person']['pers_mname'].' '.$value['person']['pers_lname']) ?>
</a>
						</td>
							<td>
<?php echo ucwords($value['person']['pers_nationality']) ?>
							</td>
<td>
<?php if ( isset($value['plots']) && !empty($value['plots']) ): ?>
	<ul>
		<?php foreach ($value['plots'] as $plots): ?>

			<?php if (!empty($plots)): ?>
				<li>
					<a href="{{route('plots.show',$plots['plot_id'])}}"><?php echo ucwords($plots['plot_number']) ?></a> &nbsp;
					( <a href="{{route('estates.show',$plots['estate']['est_id'])}}/plots"><?php echo ucwords($plots['estate']['name']) ?></a> )
				</li>				
			<?php endif ?>			
		<?php endforeach ?>
	</ul>
<?php endif ?>

</td>
							<td>
<?php echo ucwords($value['person']['pers_gender']) ?>
							</td>
							<td>{{Form::delete('customers/'. $value['cust_id'], 'Delete')}}</td>
					</tr>						
					<?php endforeach ?>
					<?php else: ?>
					<tr>
						<td colspan="7"><h4>No Customer Available!</h4></td>
					</tr>
				<?php endif ?>
			</tbody>
		</table>
	</div>
@stop
@include('templates/bottom-admin')